name         'pertino_client'
version      '0.1.2'
source       'https://github.com/Pertino/puppet_pertino.git'
author       'puppet_pertino@pertino.com'
license      'Apache License, Version 2.0'
summary      'Install and configure Pertino Client'
description  'Install and configure Pertino Clienti with Puppet'
project_page 'https://github.com/Pertino/'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
